/*
 * generated by Xtext 2.28.0
 */
package io.basicbich.oui.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import io.basicbich.oui.OuiRuntimeModule;
import io.basicbich.oui.OuiStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class OuiIdeSetup extends OuiStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new OuiRuntimeModule(), new OuiIdeModule()));
	}
	
}
