/*
 * generated by Xtext 2.28.0
 */
package io.basicbich.oui.validation;


import io.basicbich.oui.oui.*;
import org.eclipse.xtext.validation.Check;

/**
 * This class contains custom validation rules.
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class OuiValidator extends AbstractOuiValidator {
    public static final String MISSING_OBJECT_PROPERTY_KEY = "missingObjectPropertyKey";

    @Check
    public void checkOptionalObjectPropertyKey(ObjectProperty property) {
        if (property.getKey() != null) {
            return;
        }
        if (property.getValue() instanceof Selector selector) {
            final var fragments = selector.getFragments();
            if (fragments.isEmpty()) {
                if (selector.getScope() instanceof NamedSelectorScope) {
                    return;
                }
            } else {
                var lastFragment = fragments.get(fragments.size() - 1);
                if (lastFragment instanceof NamedSelectorFragment) {
                    return;
                }
            }
        }
        error("Property key is not specified and cannot be inferred from instruction", property, OuiPackage.Literals.OBJECT_PROPERTY__KEY, MISSING_OBJECT_PROPERTY_KEY);
    }
}
