/*
 * generated by Xtext 2.28.0
 */
package io.basicbich.oui.validation;


import io.basicbich.oui.oui.*;
import org.eclipse.xtext.validation.Check;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class OuiValidator extends AbstractOuiValidator {
    public static final String MISSING_OBJECT_CONSTRUCTOR_ATTRIBUTE_KEY = "missingObjectConstructorAttributeKey";

    @Check
    public void checkOptionalObjectConstructorAttributeKey(ObjectAttribute attribute) {
        if (attribute.getKey() != null) {
            return;
        }
        if (attribute.getValue() instanceof Selector) {
            var selector = (Selector) attribute.getValue();
            final var fragments = selector.getFragments();
            if (fragments.isEmpty()) {
                if (selector.getScope() instanceof NamedSelectorScope) {
                    return;
                }
            } else {
                var lastFragment = fragments.get(fragments.size() - 1);
                if (lastFragment instanceof NamedSelectorFragment) {
                    return;
                }
            }
        }
        error("Object constructor attribute name is missing", attribute, OuiPackage.Literals.OBJECT_ATTRIBUTE__KEY, MISSING_OBJECT_CONSTRUCTOR_ATTRIBUTE_KEY);
    }
}
