/*
 * generated by Xtext 2.28.0
 */
package io.basicbich.oui.validation;


import io.basicbich.oui.oui.NamedSelectorFragment;
import io.basicbich.oui.oui.NamedSelectorScope;
import io.basicbich.oui.oui.ObjectAttribute;
import io.basicbich.oui.oui.OuiPackage;
import org.eclipse.xtext.validation.Check;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class OuiValidator extends AbstractOuiValidator {
    public static final String MISSING_OBJECT_CONSTRUCTOR_ATTRIBUTE_NAME = "missingObjectConstructorAttributeName";

    @Check
    public void checkOptionalObjectConstructorAttributeName(ObjectAttribute attribute) {
        if (attribute.getName() != null) {
            return;
        }
        final var fragments = attribute.getSelector().getFragments();
        if (fragments.isEmpty()) {
            if (attribute.getSelector().getScope() instanceof NamedSelectorScope) {
                return;
            }
        } else {
            var lastFragment = fragments.get(fragments.size() - 1);
            if (lastFragment instanceof NamedSelectorFragment) {
                return;
            }
        }
        error("Object constructor attribute name is missing", attribute, OuiPackage.Literals.OBJECT_ATTRIBUTE__NAME, MISSING_OBJECT_CONSTRUCTOR_ATTRIBUTE_NAME);
    }
}
