/*
 * generated by Xtext 2.28.0
 */
package io.basicbich.oui.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class OuiWebModule extends AbstractOuiWebModule {
}
