/*
 * generated by Xtext 2.28.0
 */
package io.basicbich.oui.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import io.basicbich.oui.OuiRuntimeModule;
import io.basicbich.oui.OuiStandaloneSetup;
import io.basicbich.oui.ide.OuiIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class OuiWebSetup extends OuiStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new OuiRuntimeModule(), new OuiIdeModule(), new OuiWebModule()));
	}
	
}
