/*
 * generated by Xtext 2.28.0
 */
package io.basicbich.oui;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class OuiStandaloneSetup extends OuiStandaloneSetupGenerated {

	public static void doSetup() {
		new OuiStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
