/*
 * generated by Xtext 2.28.0
 */
package io.basicbich.oui.tests

import com.google.inject.Inject
import io.basicbich.oui.oui.Program
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import io.basicbich.oui.tests.compiler.jq.ProgramCompiler

@ExtendWith(InjectionExtension)
@InjectWith(OuiInjectorProvider)
class OuiParsingTest {
	@Inject
	ParseHelper<Program> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			$.[:] > colonne1: $.name, colonne2: $.age
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		val jqCompiler = new ProgramCompiler()
		val jqProg = jqCompiler.compile(result)
		Assertions.assertEquals(".[] | [.name, .age] | @csv", jqProg)
	}
}
