/*
 * generated by Xtext 2.28.0
 */
package io.basicbich.oui.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class OuiUiModule extends AbstractOuiUiModule {

	public OuiUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
